### ISSUE TITLE
Displayin frames not working

### ISSUE THREAD

**Issue by zsoltmazlo** [Seeed-Studio/Seeed_RGB_LED_Matrix#1]
Following [this](http://wiki.seeedstudio.com/Grove-RGB_LED_Matrix_w-Driver/) tutorial I can't display frames on the display. Every other functionality (displaying strings, numbers, emojis etc) all works well, but this one.

I'm using the very same code which enlisted under Step 4.

Tested with Arduino nano (mega328) and [M5Stack](https://docs.m5stack.com/#/en/core/basic) (ESP32).

I did changed the buffer size in both tests.

Any suggestions what can be the problem?

**Comment by tqkhcmut** [comment]
Hi,

I got the same problem. Do you have any workaround for this issue?

Thanks!

**Comment by linux-downey** [comment]
Please refer to this rep:https://github.com/linux-downey/Seeed_RGB_LED_MATRIX_V0 @zsoltmazlo

**Comment by zsoltmazlo** [comment]
Thank you @linux-downey, your solution is works like a charm! Could you please tell us what was the problem? Also it would be a nice gesture if you could make a pull-request with this fix!
